name: Check HTTP status

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Vérification toutes les heures

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Path csv file
        run: echo "SITE_CSV=data/site.csv" >> $GITHUB_ENV

      - name: Read site CSV
        run: |
          SITES=$(node site-json.js)
          echo "$SITES" >> $GITHUB_ENV

      - name: Check http status code of production site
        id: http_status
        uses: dofbi/gh-actions-http-status@v1.1
        with:
          sites: ${{ env.sites }}
          expected: ${{ env.status }}

      - name: "💫  Update README.md"
        if: failure()
        uses: "varunsridharan/action-dynamic-readme@main"
        with:
          GLOBAL_TEMPLATE_REPOSITORY: AfricTivistes/gh-action-HTTP-check-status/template
          files: |
            ./template/issue-body.md
          confirm_and_push: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STATUS: ${{ steps.http_status.outputs.failed_sites }}

      - name: Create issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Problème(s) détecté(s)
          content-filepath: ./template/issue-body.md
          labels: bug