name: Check HTTP status

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Vérification toutes les 12 heures

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm install neat-csv

      - name: Check status
        id: check_status
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '${{ fromJSON(neatCSV(fileToString("data/site.csv"))) }}'
          expected: '[200]'

      - name: Create issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: "Problème détecté sur ${{ env.SITE }}"
          body: |
            $(cat template/issue-body.md)
          labels: "bug"
          assignees: ${{ secrets.ISSUE_ASSIGNEE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SITE: ${{ steps.check_status.outputs.site }}
          STATUS: ${{ steps.check_status.outputs.status }}
